# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lacitycontribution',
            name='contributor_committee_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
